Update mac

diff --git a/builds/mac b/builds/mac
--- a/builds/mac
+++ b/builds/mac
@@ -306,19 +306,19 @@ show "Software updated!"
 inform "Checking for XCode Command Line Tools..." true
 
 # Check that command line tools are installed
-case $OS_VERSION in
-  *10.13*) cmdline_version="CLTools_Executables" ;; # High Sierra
-  *10.12*) cmdline_version="CLTools_Executables" ;; # Sierra
-  *10.11*) cmdline_version="CLTools_Executables" ;; # El Capitan
-  *10.10*) cmdline_version="CLTools_Executables" ;; # Yosemite
-  *10.9*)  cmdline_version="CLTools_Executables" ;; # Mavericks
-  *10.8*)  cmdline_version="DeveloperToolsCLI"   ;; # Mountain Lion
-  *10.7*)  cmdline_version="DeveloperToolsCLI"   ;; # Lion
-  *10.6*)  cmdline_version="DeveloperToolsCLILeo"
-           fail "Outdated OS. Considering upgrading before continuing." true;; # Snow Leopard
-           # Force the user to upgrade if they're below 10.6
-  *) fail "Sorry! You'll have to upgrade your OS to $MINIMUM_MAC_OS or above." true; exit 1;;
-esac
+# case $OS_VERSION in
+#  *10.13*) cmdline_version="CLTools_Executables" ;; # High Sierra
+#  *10.12*) cmdline_version="CLTools_Executables" ;; # Sierra
+#  *10.11*) cmdline_version="CLTools_Executables" ;; # El Capitan
+#  *10.10*) cmdline_version="CLTools_Executables" ;; # Yosemite
+#  *10.9*)  cmdline_version="CLTools_Executables" ;; # Mavericks
+#  *10.8*)  cmdline_version="DeveloperToolsCLI"   ;; # Mountain Lion
+#  *10.7*)  cmdline_version="DeveloperToolsCLI"   ;; # Lion
+#  *10.6*)  cmdline_version="DeveloperToolsCLILeo"
+#           fail "Outdated OS. Considering upgrading before continuing." true;; # Snow Leopard
+#           # Force the user to upgrade if they're below 10.6
+#  *) fail "Sorry! You'll have to upgrade your OS to $MINIMUM_MAC_OS or above." true; exit 1;;
+#esac
 
 # Check for Command Line Tools based on OS versions
 if [ ! -z $(pkgutil --pkgs=com.apple.pkg.$cmdline_version) ]; then
